repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v2.2.1" # Use the sha or tag you want to point at
      hooks:
          - id: prettier
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: "v7.23.0" # Use the sha / tag you want to point at
      hooks:
          - id: eslint
            files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
            types: [file]
            args: [--fix]
