version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    environment:
      - PORT=4000
    ports:
      - "4000:4000"
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin1}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-adminPassword}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-RESTfetchdb}
      MONGO_NON_ROOT_USERNAME: ${MONGO_NON_ROOT_USERNAME:-user1}
      MONGO_NON_ROOT_PASSWORD: ${MONGO_NON_ROOT_PASSWORD:-userPassword}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-user.sh:/docker-entrypoint-initdb.d/mongo-user.sh:ro
    command: mongod
